# Generated by Django 5.2.1 on 2025-11-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contact',
        ),
    ]
