# Generated by Django 5.2.1 on 2025-11-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0003_member_event_payment_receipt_yearlydues'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='church_momo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='welfare_momo',
            field=models.CharField(default='0123456789', max_length=15),
        ),
    ]
